//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSocialMedias
    {
        public int SocialMediaId { get; set; }
        public string SocialMediaName { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
    }
}
